# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "acbd1c7b9498523e81c489fbf223beb6"
name = "kigler Cloudflare "
handle = "kigler-cloudflare"
application_url = "https://facts-download-dig-ancient.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
dev_store_url = "test-andbuild.myshopify.com"

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://facts-download-dig-ancient.trycloudflare.com/auth/callback",
  "https://facts-download-dig-ancient.trycloudflare.com/auth/shopify/callback",
  "https://facts-download-dig-ancient.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
